#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/copilot
#    username: postgres
#    password: postgres
#  jdbc:
#    template:
#      fetch-size: 100

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/copilot
    username: postgres
    password: M1c9j812@@.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
indexer:
  base-path: /home/marcelo/IdeaProjects/cc-copilot-propertie

#  base-path: /home/marcelo/IdeaProjects
openai:
  api:
    key: SUA_CHAVE_AQUI
